import { FlashCard, FooterProps, ProfileFieldDefinition, ProfileFormData, UserProfileSummary } from '../types';

export const MOTIVATION_QUOTES: string[] = [
  'Word of the Day',
  'Quote of the Day',
  'Level Up Your Vocabulary',
  'Step to Fluency',
  'Daily Motivation',
  'Knowledge is Power',
  'Continuous Improvement',
];

export const INITIAL_FLASHCARDS: FlashCard[] = [
  {
    id: 'card-1',
    word: 'benevolent',
    translation: 'великодушный, благожелательный',
    transcription: '[bɪˈnev.əl.ənt]',
    partOfSpeech: 'adjective',
    exampleSentence: 'A benevolent smile lit up his face when he greeted the new team members.',
    exampleTranslation: 'Благожелательная улыбка озарила его лицо, когда он приветствовал новых членов команды.',
    topic: 'Personality & Character',
    level: 'B2',
  },
  {
    id: 'card-2',
    word: 'ubiquitous',
    translation: 'вездесущий, повсеместный',
    transcription: '[juːˈbɪk.wɪ.təs]',
    partOfSpeech: 'adjective',
    exampleSentence: 'Smartphones and cloud applications have become ubiquitous in modern software engineering.',
    exampleTranslation: 'Смартфоны и облачные приложения стали повсеместными в современной разработке ПО.',
    topic: 'Technology & Everyday Life',
    level: 'C1',
  },
  {
    id: 'card-3',
    word: 'serendipity',
    translation: 'счастливая случайность, интуитивная прозорливость',
    transcription: '[ˌser.ənˈdɪp.ə.ti]',
    partOfSpeech: 'noun',
    exampleSentence: 'Finding the bug through pure serendipity saved the engineering sprint two days before release.',
    exampleTranslation: 'Обнаружение бага благодаря чистой случайности спасло спринт разработки за два дня до релиза.',
    topic: 'Science & Work',
    level: 'C1',
  },
  {
    id: 'card-4',
    word: 'resilient',
    translation: 'устойчивый, жизнеспособный, упругий',
    transcription: '[rɪˈzɪl.jənt]',
    partOfSpeech: 'adjective',
    exampleSentence: 'A distributed system must be resilient to network partitions and hardware failures.',
    exampleTranslation: 'Распределенная система должна быть устойчивой к сетевым сбоям и отказам оборудования.',
    topic: 'Engineering & Resilience',
    level: 'B2',
  },
  {
    id: 'card-5',
    word: 'tenacious',
    translation: 'упорный, стойкий, цепкий',
    transcription: '[təˈneɪ.ʃəs]',
    partOfSpeech: 'adjective',
    exampleSentence: 'Her tenacious approach to code quality resolved a long-standing architectural vulnerability.',
    exampleTranslation: 'Ее упорный подход к качеству кода устранил давнюю архитектурную уязвимость.',
    topic: 'Work Ethic',
    level: 'B2',
  },
  {
    id: 'card-6',
    word: 'pragmatic',
    translation: 'прагматичный, ориентированный на практику',
    transcription: '[præɡˈmæt.ɪk]',
    partOfSpeech: 'adjective',
    exampleSentence: 'We chose a pragmatic technology stack that balances performance with maintenance costs.',
    exampleTranslation: 'Мы выбрали прагматичный технологический стек, соблюдающий баланс между производительностью и стоимостью поддержки.',
    topic: 'Architecture & Mindset',
    level: 'B1',
  },
  {
    id: 'card-7',
    word: 'meticulous',
    translation: 'скрупулезный, тщательный',
    transcription: '[məˈtɪk.jə.ləs]',
    partOfSpeech: 'adjective',
    exampleSentence: 'Writing comprehensive unit tests requires meticulous attention to edge cases.',
    exampleTranslation: 'Написание подробных модульных тестов требует скрупулезного внимания к пограничным случаям.',
    topic: 'Quality Assurance',
    level: 'B2',
  },
  {
    id: 'card-8',
    word: 'lucid',
    translation: 'ясный, понятный, прозрачный',
    transcription: '[ˈluː.sɪd]',
    partOfSpeech: 'adjective',
    exampleSentence: 'The technical documentation was so lucid that onboarding took only a single afternoon.',
    exampleTranslation: 'Техническая документация была настолько ясной, что онбординг занял всего одну половину дня.',
    topic: 'Documentation & Communication',
    level: 'B2',
  },
];

export const PROFILE_FIELDS_20: ProfileFieldDefinition[] = [
  // 1. String
  {
    id: 'fullName',
    name: 'fullName',
    label: 'ФИО сотрудника',
    type: 'string',
    placeholder: 'Гончаров Максим Александрович',
    required: true,
    helperText: 'Полное имя для отображения в профиле и корпоративной системе',
  },
  // 2. String
  {
    id: 'email',
    name: 'email',
    label: 'Корпоративный Email',
    type: 'string',
    placeholder: 'goncharov.m@astral.ru',
    required: true,
    helperText: 'Используется для уведомлений и доступа к рабочим сервисам',
  },
  // 3. String
  {
    id: 'phone',
    name: 'phone',
    label: 'Контактный телефон',
    type: 'string',
    placeholder: '+7 (999) 000-00-00',
    required: true,
    helperText: 'Телефон для двухфакторной аутентификации и срочной связи',
  },
  // 4. String
  {
    id: 'city',
    name: 'city',
    label: 'Город проживания',
    type: 'string',
    placeholder: 'Калуга',
    required: true,
    helperText: 'Фактическое местоположение сотрудника',
  },
  // 5. Date
  {
    id: 'birthDate',
    name: 'birthDate',
    label: 'Дата рождения',
    type: 'date',
    required: true,
    helperText: 'Необходима для кадрового учета и поздравлений команды',
  },
  // 6. Number
  {
    id: 'targetSalary',
    name: 'targetSalary',
    label: 'Ожидаемая заработная плата (руб.)',
    type: 'number',
    placeholder: '160000',
    min: 30000,
    max: 1000000,
    required: true,
    helperText: 'Желаемый уровень дохода на руки (net)',
  },
  // 7. Number
  {
    id: 'experienceYears',
    name: 'experienceYears',
    label: 'Опыт коммерческой разработки (в годах)',
    type: 'number',
    placeholder: '3',
    min: 0,
    max: 40,
    required: true,
    helperText: 'Стаж участия в коммерческих проектах',
  },
  // 8. Select
  {
    id: 'primaryRole',
    name: 'primaryRole',
    label: 'Основная специализация',
    type: 'select',
    required: true,
    options: [
      { label: 'Frontend Developer (React/TS)', value: 'frontend' },
      { label: 'Backend Developer (Node/Go/Java)', value: 'backend' },
      { label: 'Fullstack Engineer', value: 'fullstack' },
      { label: 'QA Automation Engineer', value: 'qa' },
      { label: 'DevOps / Infrastructure', value: 'devops' },
    ],
    helperText: 'Ключевое направление вашей профессиональной экспертизы',
  },
  // 9. Select
  {
    id: 'englishLevel',
    name: 'englishLevel',
    label: 'Уровень владения английским языком',
    type: 'select',
    required: true,
    options: [
      { label: 'A1 — Beginner', value: 'A1' },
      { label: 'A2 — Elementary', value: 'A2' },
      { label: 'B1 — Intermediate', value: 'B1' },
      { label: 'B2 — Upper-Intermediate', value: 'B2' },
      { label: 'C1 — Advanced', value: 'C1' },
    ],
    helperText: 'Для чтения документации и взаимодействия с зарубежными библиотеками',
  },
  // 10. Radio (FIELD A - TRIGGERS DEPENDENCIES)
  {
    id: 'employmentType',
    name: 'employmentType',
    label: 'Поле А: Тип трудоустройства (управляющее зависимостями)',
    type: 'radio',
    required: true,
    options: [
      { label: 'Полная занятость (Full-time)', value: 'full_time' },
      { label: 'Частичная занятость (Part-time)', value: 'part_time' },
      { label: 'Стажировка / Студент (Internship)', value: 'intern' },
    ],
    helperText: 'При выборе «Стажировка / Студент»: Поле Б скроется, а Поле В заблокируется со значением «Обязательно»',
  },
  // 11. Select (FIELD B - DEPENDENT: HIDDEN WHEN FIELD A IS 'intern')
  {
    id: 'officeCity',
    name: 'officeCity',
    label: 'Поле Б: Офис присутствия (скрывается при стажировке)',
    type: 'select',
    required: false,
    options: [
      { label: 'Калуга — Главный хаб ГК Астрал (ул. Циолковского, 4)', value: 'kaluga' },
      { label: 'Москва — Бизнес-центр Водный', value: 'moscow' },
      { label: 'Санкт-Петербург — Невский центр', value: 'spb' },
      { label: 'Удаленный контракт без привязки к офису', value: 'remote_only' },
    ],
    helperText: 'Локация корпоративного офиса для очных встреч и мероприятий',
  },
  // 12. Select (FIELD C - DEPENDENT: DISABLED & PRESET WHEN FIELD A IS 'intern')
  {
    id: 'mentorshipRequired',
    name: 'mentorshipRequired',
    label: 'Поле В: Необходимость наставника (блокируется со спец-значением при стажировке)',
    type: 'select',
    required: true,
    options: [
      { label: 'Не требуется (самостоятельная разработка)', value: 'none' },
      { label: 'Периодические 1-on-1 консультации', value: 'optional' },
      { label: 'Обязательно требуется закрепленный ментор (Senior)', value: 'mandatory' },
    ],
    helperText: 'Уровень поддержки со стороны ведущих инженеров команды',
  },
  // 13. Radio
  {
    id: 'workFormat',
    name: 'workFormat',
    label: 'Предпочтительный формат работы',
    type: 'radio',
    required: true,
    options: [
      { label: 'Полностью удаленная работа (Remote)', value: 'remote' },
      { label: 'Гибридный график (1-2 дня в офисе)', value: 'hybrid' },
      { label: 'Постоянная работа в офисе', value: 'office' },
    ],
    helperText: 'Определяет организацию рабочего процесса и оснащение рабочего места',
  },
  // 14. Checkbox Group
  {
    id: 'skills',
    name: 'skills',
    label: 'Ключевые технологии и навыки (стек)',
    type: 'checkbox',
    options: [
      { label: 'React 18+', value: 'react' },
      { label: 'TypeScript (Strict Mode)', value: 'typescript' },
      { label: 'Redux Toolkit / RTK Query', value: 'redux' },
      { label: 'Next.js & Server Components', value: 'nextjs' },
      { label: 'Tailwind CSS / PostCSS', value: 'tailwind' },
      { label: 'Unit/Integration Tests (Jest/Vitest)', value: 'tests' },
      { label: 'Docker & Docker Compose', value: 'docker' },
      { label: 'REST API & WebSockets', value: 'rest' },
    ],
    helperText: 'Отметьте технологии, с которыми имеете реальный производственный опыт',
  },
  // 15. Select
  {
    id: 'education',
    name: 'education',
    label: 'Уровень образования',
    type: 'select',
    required: true,
    options: [
      { label: 'Высшее техническое / информатика', value: 'higher_tech' },
      { label: 'Высшее профильное (математика, физика)', value: 'higher_stem' },
      { label: 'Среднее профессиональное (колледж IT)', value: 'college' },
      { label: 'Профильная переподготовка / Курсы', value: 'courses' },
      { label: 'Самообразование', value: 'self_taught' },
    ],
    helperText: 'Академическая база соискателя',
  },
  // 16. String
  {
    id: 'currentTraining',
    name: 'currentTraining',
    label: 'Текущее обучение и повышение квалификации',
    type: 'string',
    placeholder: 'Углубленная архитектура фронтенда и веб-производительность (вечером/в выходные)',
    required: false,
    helperText: 'Как совмещается с рабочим графиком',
  },
  // 17. String
  {
    id: 'githubUrl',
    name: 'githubUrl',
    label: 'Ссылка на репозиторий GitHub / GitLab',
    type: 'string',
    placeholder: 'https://github.com/GoncharovMaksim',
    required: false,
    helperText: 'Публичный код, пет-проекты или вклад в Open Source',
  },
  // 18. Number
  {
    id: 'portfolioProjectsCount',
    name: 'portfolioProjectsCount',
    label: 'Количество завершенных коммерческих проектов',
    type: 'number',
    placeholder: '6',
    min: 0,
    max: 100,
    required: false,
    helperText: 'Число крупных проектов, выведенных в продакшен',
  },
  // 19. Select
  {
    id: 'preferredNotificationTime',
    name: 'preferredNotificationTime',
    label: 'Удобное время для коммуникации',
    type: 'select',
    required: true,
    options: [
      { label: 'Утренний слот (09:00 — 12:00 МСК)', value: 'morning' },
      { label: 'Дневной слот (12:00 — 16:00 МСК)', value: 'day' },
      { label: 'Вечерний слот (16:00 — 19:00 МСК)', value: 'evening' },
    ],
    helperText: 'Оптимальное окно для синхронизаций с тимлидом и HR',
  },
  // 20. Text / Textarea
  {
    id: 'aboutBio',
    name: 'aboutBio',
    label: 'О себе и мотивация работы в ГК Астрал',
    type: 'text',
    placeholder: 'Опытный фронтенд-разработчик. Создаю надежные, типизированные SPA с высокой производительностью и чистой архитектурой. Вдохновляет масштабируемость экосистемы сервисов Астрал.',
    required: false,
    helperText: 'Краткое резюме сильных сторон и профессиональных целей',
  },
];

export const INITIAL_PROFILE_VALUES: ProfileFormData = {
  fullName: 'Гончаров Максим Александрович',
  email: 'goncharov.m@astral.ru',
  phone: '+7 (999) 123-45-67',
  city: 'Калуга',
  birthDate: '1996-05-18',
  targetSalary: 160000,
  experienceYears: 3,
  primaryRole: 'frontend',
  englishLevel: 'B2',
  employmentType: 'full_time',
  officeCity: 'kaluga',
  mentorshipRequired: 'optional',
  workFormat: 'remote',
  skills: ['react', 'typescript', 'redux', 'tailwind', 'tests', 'rest'],
  education: 'higher_tech',
  currentTraining: 'Курс по микрофронтендам и оптимизации Core Web Vitals (в свободное время)',
  githubUrl: 'https://github.com/GoncharovMaksim',
  portfolioProjectsCount: 5,
  preferredNotificationTime: 'day',
  aboutBio: 'Middle Frontend разработчик с 3+ годами коммерческого опыта в экосистеме React, Redux Toolkit и TypeScript. Стремлюсь создавать поддерживаемый, протестированный код и удобные интерфейсы для корпоративных пользователей.',
};

export const FAKE_USER: UserProfileSummary = {
  username: 'admin',
  fullName: 'Максим Гончаров',
  email: 'goncharov.m@astral.ru',
  role: 'Middle Frontend Developer',
  avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&auto=format&fit=crop&q=80',
};

export const FAKE_FOOTER_DATA: FooterProps = {
  companyName: 'ГК Калуга Астрал',
  email: 'hr@astral.ru',
  phone: '8 (800) 700-86-68',
  address: '248023, г. Калуга, пер. Теренинский, д. 9',
  copyright: '© 1993–2026 Группа компаний «Астрал». Все права защищены.',
  links: [
    { title: 'Вакансии компании', href: 'https://astral.ru/career/' },
    { title: 'О компании', href: 'https://astral.ru/about/' },
    { title: 'ИТ-продукты', href: 'https://astral.ru/products/' },
  ],
};
